name: Test

on:
    pull_request: {}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: go test -v ./...